parameters:
    # Adds a fallback configuration if the env var is not set.
    env(MJ_API_KEY):        'ThisIsSecretApiKey'
    env(MJ_SECRET_KEY):     'ThisIsSecretApiPwd'
    env(MJ_API_LIST):       'ThisIsSecretApiList'

splash:
    ################################################################################
    # List of Available Connector Connections
    ################################################################################
    connections:
        
        ########################################################################
        # MailJet Staging / Real Connexion
        staging:
            id:                 ThisIsMailjetWsId
            key:                ThisIsNotASecretKeyForMailjet
            name:               Mailjet - Staging
            connector:          mailjet
            config:
                Extended:       true
                WsHost:         http://localhost:8000
                ApiKey:         "%env(resolve:MJ_API_KEY)%"
                SecretKey:      "%env(resolve:MJ_SECRET_KEY)%"
                ApiList:        "%env(resolve:MJ_API_LIST)%"

        ########################################################################
        # MailJet Sandbox
        sandbox:
            id:                 ThisIsMailjetSandboxWsId
            key:                ThisIsNotASecretKeyForMailjetSandbox
            name:               Mailjet - Sandbox
            connector:          mailjet
            config:
                Extended:       true
                isSandbox:      true
                WsHost:         http://sandbox.mailjet.local
                ApiKey:         "ThisIsSecretApiKey"
                SecretKey:      "ThisIsSecretApiPwd"
                ApiList:        "%env(resolve:MJ_API_LIST)%"
