api_platform:
    title: Mailjet API SandBox
    defaults:
        formats: ['json']
        stateless: false
    swagger:
        api_keys:
            - { name: "api-key", key: "api-key", type: "header" }
    collection:
        pagination:
            enabled: true
            items_per_page_parameter_name: limit

services:

    ########################################################################
    # Mailjet Normalizer
    App\Serializer\ApiNormalizer:
        decorates: 'api_platform.serializer.normalizer.item'
        arguments:
            $decorated: '@App\Serializer\ApiNormalizer.inner'

framework:
    router:
        utf8: true
