services:

    _defaults:
        autowire:           true
        autoconfigure:      true


    ################################################################################
    # Autowire for Mailjet Connector
    Splash\Connectors\Mailjet\Connectors\:
        resource: '../../Connectors'

    ################################################################################
    # Enables Dependency Injection in Actions
    Splash\Connectors\Mailjet\Actions\:
        resource: '../../Actions'
        public: true
        tags: ['controller.service_arguments']

    ################################################################################
    # Autowire for Mailjet Services
    Splash\Connectors\Mailjet\Services\:
        resource: '../../Services'