services:

    _defaults:
        autowire:           true
        autoconfigure:      true

    ################################################################################
    # SPLASH Mailjet Connector Service
    splash.connectors.mailjet:
        class: Splash\Connectors\Mailjet\Services\MailjetConnector
        arguments:  [ "@event_dispatcher", "@logger" ]
        tags:       
            - { name: "splash.connector"}

    ################################################################################
    # Enables Dependency Injection in Actions
    Splash\Connectors\Mailjet\Actions\:
        resource: '../../Actions'
        public: true
        tags: ['controller.service_arguments']
