
splash:

################################################################################    
# Configure Splash Bundle Parameters Cache    
# Cache is Enabled by Default to Store Custom Connectors Configuration
# If disabled, configuration must be store in Static, on connections section
################################################################################    
#    cache: 
#        enabled: false    
#        lifetime: 10

    # Allow Notifications for Generic Users   
    notify: ["ROLE_USER"]
    
################################################################################    
# List of Availables Connector Connections
################################################################################    

    connections:
        
        ########################################################################
        # MailJet Default
        mailjet:
            id:                 ThisIsMailjetWsId
            key:                ThisIsNotASecretKeyForMailjet
            name:               Serveur 1 (Mailjet)
            connector:          mailjet
            config:
                WsHost:         http://localhost:8000
                ApiKey:         ThisIsSecretApiKey
                SecretKey:      ThisIsSecretApiPwd
                ApiList:        ThisIsSecretApiList
